from perceptron import Perceptron

p = Perceptron('pa3train.txt', 'pa3test.txt', 'pa3dictionary.txt')
p.training(1, 2, first = True)
p.opt_training(1,2)
print('first pass')
print('perceptron')
print(p.error(p.train,1,2))
print('voted perceptron')
print(p.v_error(p.train,1,2))
print('average perceptron')
print(p.a_error(p.train,1,2))
print('\n')

print('second pass')
p.training(1,2)
p.opt_training(1,2)
print('perceptron')
print(p.error(p.train,1,2))
print('voted perceptron')
print(p.v_error(p.train,1,2))
print('average perceptron')
print(p.a_error(p.train,1,2))
print('\n')

print('third pass')
p.training(1,2)
p.opt_training(1,2)
print('perceptron')
print(p.error(p.train,1,2))
print('voted perceptron')
print(p.v_error(p.train,1,2))
print('average perceptron')
print(p.a_error(p.train,1,2))
print('\n')

print('fourth pass')
p.training(1,2)
p.opt_training(1,2)
print('perceptron')
print(p.error(p.train,1,2))
print('voted perceptron')
print(p.v_error(p.train,1,2))
print('average perceptron')
print(p.a_error(p.train,1,2))
print('\n')

print('Test Error')
p1 = Perceptron('pa3train.txt', 'pa3test.txt', 'pa3dictionary.txt')
p1.training(1, 2, first = True)
p1.opt_training(1,2)
print('first pass')
print('perceptron')
print(p1.error(p1.test,1,2))
print('voted perceptron')
print(p1.v_error(p1.test,1,2))
print('average perceptron')
print(p1.a_error(p1.test,1,2))
print('\n')

print('second pass')
p1.training(1,2)
p1.opt_training(1,2)
print('perceptron')
print(p1.error(p1.test,1,2))
print('voted perceptron')
print(p.v_error(p1.test,1,2))
print('average perceptron')
print(p1.a_error(p1.test,1,2))
print('\n')

print('third pass')
p1.training(1,2)
p1.opt_training(1,2)
print('perceptron')
print(p1.error(p1.test,1,2))
print('voted perceptron')
print(p1.v_error(p1.test,1,2))
print('average perceptron')
print(p1.a_error(p1.test,1,2))
print('\n')

print('fourth pass')
p1.training(1,2)
p1.opt_training(1,2)
print('perceptron')
print(p1.error(p1.test,1,2))
print('voted perceptron')
print(p1.v_error(p1.test,1,2))
print('average perceptron')
print(p1.a_error(p1.test,1,2))
print('\n')
